Server:
  port: "8090"
  mode: "release"

Database:
  # 数据库类型: mysql 或 sqlite (默认: mysql)
  # # MySQL 配置 (当 type 为 mysql 时使用)
  # host: 127.0.0.1
  # port: 3306
  # user: root
  # pass: 1q2w3e4r
  # dbName: aimodel
  # timeout: 10s
  type: sqlite
  # MySQL 配置 (当 type 为 mysql 时使用)
  dbName: aimodel
  timeout: 10s
  # SQLite 配置 (当 type 为 sqlite 时使用)
  path: data/ai.db

Jwt:
  expire: 18000